modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="sparklesoup"
version="1.0.0"
displayName="Sparkle Soup"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="mostwonderfulboy"
description='''
Adds a soup which lets you fly!
'''

[[dependencies.sparklesoup]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



